DROP DATABASE IF EXISTS ne1w6jye515g3cal;

CREATE DATABASE ne1w6jye515g3cal;

USE ne1w6jye515g3cal;

CREATE TABLE burgers (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  burger_name VARCHAR(42) UNIQUE NOT NULL,
  devoured BOOL NOT NULL
);